# Generated by Django 5.2.2 on 2025-06-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_produk/'),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.CharField(choices=[('kue kering', 'Kue Kering'), ('kue basah', 'Kue Basah'), ('roti', 'Roti'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
    ]
