# Generated by Django 5.2.2 on 2025-06-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produk_gambar_produk_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.CharField(choices=[('kue kering', 'Kue Kering'), ('kue basah', 'Kue Basah'), ('roti', 'Roti'), ('spesial', 'Spesial')], default='lainnya', max_length=20),
        ),
    ]
